### ISSUE TITLE
pdf diseño de cajas de texto

### ISSUE THREAD

**Issue by Edwin38H** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-Edwin38H#2]
[TextBox.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-Edwin38H/files/6341161/TextBox.pdf)

**Comment by carlos-chrs** [comment]
calificado 
100

**Comment by josealfredo79** [comment]
La calificacion máxima es de 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
